### ISSUE TITLE
Dark Button Wizard Improvements

### ISSUE THREAD

**Issue by ryantheleach** [Moltenkore/darkprograms#3]
UI Improvements for button.

It would be great if there was a grid or alternating checkerboard pattern to make it easier to select the buttons where you want when using the wizard.

**Comment by Moltenkore** [comment]
I'm not too sure what you mean

**Comment by ryantheleach** [comment]
when clicking the screens to create the button there is currently no way to tell where the edge of the button will be, if the background was all X's or alternating colors, you would be able to see the characters that the button's edge would align to.

**Comment by Moltenkore** [comment]
Ah I see, yes that's a great idea. i'll get on to implementing that soon!

**Comment by Moltenkore** [comment]
Added!
